#
# Copyright (C) 2022-2023 hugcabbage <fengsongtianxia@gmail.com>
#
# This is free software, licensed under the MIT License.
#
# <https://github.com/hugcabbage/shared-lede>
#
# 源码采用coolsnowwolf lede
#
name: 固件编译 lede

on:
  workflow_dispatch:
    inputs:
      build:
        description: '若要编译固件，请输入true'
        required: true
        default: 'true'
        type: string
      model:
        description: '选择设备'
        required: true
        type: choice
        options:
          - 'xiaomi-4a-gigabit'
          - 'xiaomi-3g-v2'
          - 'xiaomi-cr6608'
          - 'xiaomi-cr6606'
          - 'xiaomi-cr6609'
          - 'xiaomi-3g'
          - 'xiaomi-4'
          - 'xiaomi-3-pro'
          - 'redmi-ac2100'
          - 'xiaomi-ac2100'
          - 'phicomm-k2p'
          - 'redmi-ax6s'
          - 'xiaomi-4a-100m'
          - 'xiaomi-4c'
          - 'miwifi-nano'
          - 'glinet-mt300n-v2'
          - 'glinet-microuter-n300'
          - 'miwifi-mini'
          - 'miwifi-r3'
      lan_ipad:
        description: '设置LAN口IP地址(会覆盖modify脚本中的设置)'
        required: false
        default: ''
        type: string
      record:
        description: '输入版本描述'     
        required: false
        default: '升级内容：内核升级，更新应用版本'
        type: string
      cpu_overclock:
        description: '超频到1100Mhz(仅适用于5.10内核)'
        required: false
        type: boolean
      kernel_5_15:
        description: '使用5.15内核'
        required: false
        type: boolean
      release:
        description: '上传到release'
        required: false
        default: true
        type: boolean
      artifact:
        description: '上传到artifact'
        required: false
        type: boolean

jobs:
  build:
    name: 测试编译 lede
    if: inputs.build == 'true'
    runs-on: ubuntu-latest
    env:
      TEMP_PREFIX: temp
      DEPLOYDIR: preset-lede
    steps:

      - name: 初始空间情况
        run: |
          df -h

      - name: Checkout
        uses: actions/checkout@v3

      - name: 环境准备
        run: |
          sudo apt-get update
          sudo apt-get -y install gcc-multilib gettext libncurses5-dev
          sudo apt-get clean
          pip3 install -r extra-files/requirements-transit.txt

      - name: 读取配置
        env:
          MODEL_NAME: ${{ inputs.model }}
        run: |
          python3 extra-files/transit.py

      - name: 下载源码与插件
        env:
          CLONE_SH: ${{ env.DEPLOYDIR }}/${{ env.TEMP_PREFIX }}.clone.sh
        run: |
          chmod +x $CLONE_SH
          $CLONE_SH

      - name: 升级feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 修改配置
        env:
          MODIFY_SH: ${{ env.DEPLOYDIR }}/${{ env.TEMP_PREFIX }}.modify.sh
        run: |
          ${{ inputs.cpu_overclock }} && \
            sed -i '/fix-cpu-clk-add-clkdev/ s/#//' $MODIFY_SH
          ${{ inputs.kernel_5_15 }} && \
            sed -i '/KERNEL_PATCHVER:=5.15/ s/#//' $MODIFY_SH
          chmod +x $MODIFY_SH
          $MODIFY_SH
          ${{ inputs.lan_ipad != '' }} && \
            sed -i "/lan) ipad=/clan) ipad=\${ipaddr:-\"${{ inputs.lan_ipad }}\"} ;;" \
              package/base-files/files/bin/config_generate
          cat package/base-files/files/etc/banner
          :

      - name: 空间使用情况
        run: |
          df -h
          echo "----------------------------"
          du -h --max-depth=1
